# name: qiita-files CI

on:
  push:
    branches: [ dev ]
  pull_request:

jobs:
  # derived from https://github.com/actions/example-services/blob/master/.github/workflows/postgres-service.yml
  main:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            python-version: ["3.6", "3.9", "3.10", "3.11", "3.12"]
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup for conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Basic dependencies install
        shell: bash -l {0}
        run: |
          conda create --yes -n qiita-files python=${{ matrix.python-version }} h5py pandas scipy numpy
          conda activate qiita-files
          pip install .
          pip install sphinx sphinx-bootstrap-theme pytest-cov codecov Click

      - name: Main tests
        shell: bash -l {0}
        run: |
          conda activate qiita-files
          pytest --doctest-modules --cov=qiita_files --cov-report=lcov

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: flake8
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: install dependencies
      run: python -m pip install --upgrade pip
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: lint
      run: |
        pip install -q flake8
        flake8 qiita_files setup.py
